language: python
python:
    - 2.7
install:
    - pip install -r requirements.txt
script:
    - nosetests -v --with-coverage --cover-package=mooc_aggregator_restful_api --cover-inclusive --cover-erase tests
notifications:
    email: false
